# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_ARCHIVE_GID "-1")
set(CPACK_ARCHIVE_UID "-1")
set(CPACK_BUILD_SOURCE_DIRS "D:/GitHub/Jakal-Core;D:/GitHub/Jakal-Core/build_ninja")
set(CPACK_CMAKE_GENERATOR "Ninja")
set(CPACK_COMPONENTS_ALL "runtime;development;docs;maintenance")
set(CPACK_COMPONENTS_ALL_SET_BY_USER "TRUE")
set(CPACK_COMPONENT_DEVELOPMENT_DISPLAY_NAME "Development Files")
set(CPACK_COMPONENT_DOCS_DISPLAY_NAME "Documentation")
set(CPACK_COMPONENT_MAINTENANCE_DISPLAY_NAME "Maintenance Tools")
set(CPACK_COMPONENT_RUNTIME_DISPLAY_NAME "Runtime")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "C:/Program Files/CMake/share/cmake-4.3/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "JakalCore built using CMake")
set(CPACK_DMG_SLA_USE_RESOURCE_FILE_LICENSE "ON")
set(CPACK_GENERATOR "7Z;ZIP")
set(CPACK_IGNORE_FILES "/CVS/;/\\.svn/;/\\.bzr/;/\\.hg/;/\\.git/;\\.swp\$;\\.#;/#")
set(CPACK_INNOSETUP_ARCHITECTURE "x64")
set(CPACK_INSTALLED_DIRECTORIES "D:/GitHub/Jakal-Core;/")
set(CPACK_INSTALL_CMAKE_PROJECTS "")
set(CPACK_INSTALL_PREFIX "C:/Program Files (x86)/JakalCore")
set(CPACK_MODULE_PATH "")
set(CPACK_NSIS_CREATE_ICONS_EXTRA "CreateShortCut \"$SMPROGRAMS\\$STARTMENU_FOLDER\\Jakal Hardware Setup.lnk\" \"$INSTDIR\\bin\\launch-jakal-hardware-setup.cmd\" \"\" \"$INSTDIR\\bin\\jakal-core-logo.ico\" 0")
set(CPACK_NSIS_DELETE_ICONS_EXTRA "Delete \"$SMPROGRAMS\\$STARTMENU_FOLDER\\Jakal Hardware Setup.lnk\"")
set(CPACK_NSIS_DISPLAY_NAME "Jakal-Core")
set(CPACK_NSIS_DISPLAY_NAME_SET "TRUE")
set(CPACK_NSIS_ENABLE_UNINSTALL_BEFORE_INSTALL "ON")
set(CPACK_NSIS_EXECUTABLE "D:/GitHub/Jakal-Core/tools/nsis/portable/nsis-3.11/makensis.exe")
set(CPACK_NSIS_INSTALLED_ICON_NAME "bin\\jakal-core-logo.ico")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "!define MUI_ICON \"D:\\GitHub\\Jakal-Core\\build_ninja\\branding\\jakal-core-logo.ico\"
!define MUI_UNICON \"D:\\GitHub\\Jakal-Core\\build_ninja\\branding\\jakal-core-logo.ico\"")
set(CPACK_NSIS_INSTALLER_MUI_WELCOMEFINISH_CODE "!define MUI_HEADERIMAGE_BITMAP \"D:\\GitHub\\Jakal-Core\\build_ninja\\branding\\jakal-core-logo-header.bmp\"
!define MUI_HEADERIMAGE_UNBITMAP \"D:\\GitHub\\Jakal-Core\\build_ninja\\branding\\jakal-core-logo-header.bmp\"
!define MUI_WELCOMEFINISHPAGE_BITMAP \"D:\\GitHub\\Jakal-Core\\build_ninja\\branding\\jakal-core-logo-wizard.bmp\"
!define MUI_UNWELCOMEFINISHPAGE_BITMAP \"D:\\GitHub\\Jakal-Core\\build_ninja\\branding\\jakal-core-logo-wizard.bmp\"
")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES64")
set(CPACK_NSIS_MENU_LINKS "bin\\jakal_bootstrap.exe;Jakal Bootstrap;bin\\launch-jakal-hardware-setup.cmd;Jakal Hardware Setup;share\\doc\\JakalCore\\README.md;README")
set(CPACK_NSIS_MODIFY_PATH "OFF")
set(CPACK_NSIS_MUI_FINISHPAGE_RUN "bin\\launch-jakal-hardware-setup.cmd")
set(CPACK_NSIS_PACKAGE_NAME "Jakal-Core")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OUTPUT_CONFIG_FILE "D:/GitHub/Jakal-Core/build_ninja/CPackConfig.cmake")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "C:/Program Files/CMake/share/cmake-4.3/Templates/CPack.GenericDescription.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Graph-first heterogeneous compute runtime skeleton")
set(CPACK_PACKAGE_FILE_NAME "Jakal-Core-0.1.0-Source")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "Jakal-Core")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "Jakal-Core")
set(CPACK_PACKAGE_NAME "Jakal-Core")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "Jakal")
set(CPACK_PACKAGE_VERSION "0.1.0")
set(CPACK_PACKAGE_VERSION_MAJOR "0")
set(CPACK_PACKAGE_VERSION_MINOR "1")
set(CPACK_PACKAGE_VERSION_PATCH "0")
set(CPACK_RESOURCE_FILE_LICENSE "D:/GitHub/Jakal-Core/LICENSE")
set(CPACK_RESOURCE_FILE_README "D:/GitHub/Jakal-Core/README.md")
set(CPACK_RESOURCE_FILE_WELCOME "C:/Program Files/CMake/share/cmake-4.3/Templates/CPack.GenericWelcome.txt")
set(CPACK_RPM_PACKAGE_SOURCES "ON")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_7Z "ON")
set(CPACK_SOURCE_GENERATOR "7Z;ZIP")
set(CPACK_SOURCE_IGNORE_FILES "/CVS/;/\\.svn/;/\\.bzr/;/\\.hg/;/\\.git/;\\.swp\$;\\.#;/#")
set(CPACK_SOURCE_INSTALLED_DIRECTORIES "D:/GitHub/Jakal-Core;/")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "D:/GitHub/Jakal-Core/build_ninja/CPackSourceConfig.cmake")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "Jakal-Core-0.1.0-Source")
set(CPACK_SOURCE_TOPLEVEL_TAG "win64-Source")
set(CPACK_SOURCE_ZIP "ON")
set(CPACK_STRIP_FILES "")
set(CPACK_SYSTEM_NAME "win64")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "win64-Source")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "D:/GitHub/Jakal-Core/build_ninja/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
